### ISSUE TITLE
请问一下服务器怎么搭建?

### ISSUE THREAD

**Issue by ErQing** [inspoy/BounceArena#1]
没有接触过Node.js 博主能写下博客吗 ? 感谢

**Comment by inspoy** [comment]
最近有点忙orz，之后有空整理下这个项目写个完结篇~

**Comment by ErQing** [comment]
非常感谢博主！

**Comment by inspoy** [comment]
博客已经更新了，在README里面有链接，文末有我的个人公众号，有问题可以通过那个给我留言

**Comment by ErQing** [comment]
看到了 ! 非常感谢博主 , 祝博主独立游戏获得成功 !
